### ISSUE TITLE
[Toolkit bug]: Objects tagged in the runtime as decal, sky or anything aren't selectable inside toolkit

### ISSUE THREAD

**Issue by tadpole3159** [NVIDIAGameWorks/rtx-remix#531]
### Describe the bug

Right so when your working on your game you tag textures in the run time. this thing a decal, this things sky...ect Then you perform a capture and open it in toolkit and that's where this problem happens. you can't select things you mark as decal or sky to edit them

https://github.com/NVIDIAGameWorks/rtx-remix/assets/134654759/c841fe14-eeae-46d4-9c8f-58544d1c23ca

### How do you reproduce the bug?

Mark an object as decal or sky, capture usd and try to select the object in toolkit. 

### What is the expected behavior?

allow me to pick these objects so I can attach lights or mesh replacements to them, I cant even select them to change the material inputs

### Version

2024.3.1

**Comment by Arrokoth7323** [comment]
Concur with this post, any objects marked as Sky become treated as a literal skybox in the Toolkit. Would love clarification as to if this is by design.

**Comment by sjgillard** [comment]
Does this happen with all the decals? I know there are a few different decal types.

**Comment by sjgillard** [comment]
Jira created: REMIX-3133

**Comment by tadpole3159** [comment]
> Does this happen with all the decals? I know there are a few different decal types.

they're used to be lots of decal options, now it's just one called "decal"
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/134654759/9b65e24c-a3db-4fba-b9f2-4935b0a60ca7)

**Comment by xoxor4d** [comment]
Possible dupe: https://github.com/NVIDIAGameWorks/rtx-remix/issues/487

**Comment by nxkb** [comment]
So decals should be fixed in the next release (2024.5). Sky (and a few others) will have to have their own fix because of the way objects tagged as such become un-selectable.

**Comment by tadpole3159** [comment]
@NV-LL Hi, thank you! I just got it downloaded and have confirmed that I can select decals now. I see the tag in the object properties so i know i have it selected
![image](https://github.com/user-attachments/assets/ff124eb7-f273-42f3-a347-fcdf35bb1f69)
I'm going to suggest we keep this bug open though as I still cant select the sky

**Comment by nxkb** [comment]
Another update here to say that you can now find these objects via the Stage Manager (Main Menu > Experimental Features) in a new Remix "Categories" Tab. Clicking on the object there should select the prim.

Selecting the objects tagged as "sky" via the viewport is still a known issue, but solving that properly will require adding more expansive renderer options to selectively ignore the effect of a category for viewport selection.

**Comment by tadpole3159** [comment]
> Another update here to say that you can now find these objects via the Stage Manager (Main Menu > Experimental Features) in a new Remix "Categories" Tab. Clicking on the object there should select the prim.
> 
> Selecting the objects tagged as "sky" via the viewport is still a known issue, but solving that properly will require adding more expansive renderer options to selectively ignore the effect of a category for viewport selection.

That's brilliant, anything to save me having to edit a USDA in notepad. Tested and worked in latest toolkit. Would you like me to close the blue or do you plan to fix the viewport selection issue?

**Comment by nyleusmani** [comment]
Please close it @tadpole3159 .
