### ISSUE TITLE
Tomb Raider: Angel of Darkness injecting but not rendering properly

### ISSUE THREAD

**Issue by svelle** [NVIDIAGameWorks/rtx-remix#80]
**Describe the bug**
- Game can not startup regularly. The game throws an error after launching (could be the intro files, because it launches just fine if you disable those, but then the game can't launch because of an error of it not finding the game files...) 
- Directly loading into the game via a third party app works (TRAOD SCU). After getting into the game there's a yellow overlay on the screen and the player character is invisible. 

This is the error thrown with the videos enabled: 
![image](https://user-images.githubusercontent.com/7526550/232227139-2744b30e-45bf-4b24-9db1-074cb3ffd541.png)

This is the error with the videos disabled: 
![image](https://user-images.githubusercontent.com/7526550/232227177-72287274-701a-44d4-b5f7-e936239e28fd.png)

Game looks like this when manually loading into a level:
![image](https://user-images.githubusercontent.com/7526550/232227495-6fd2535d-8bed-428d-9d20-ddce5daa285c.png)

Also to make the mouse work in the overlay you have to disable the mouse in the game.

- Which Remix version: 0.1.1
- Which GPU: RTX 4080
- Which GPU driver version: 531.41
- Which game build: Steam

Logs for the crash in the beginning with enabled videos:
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239614/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239613/d3d9.log)
- [TRAOD_P4_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239610/TRAOD_P4_d3d9.log)

Logs from the game, when manually loading into a level:
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239622/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239623/d3d9.log)
- [TRAOD_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11239624/TRAOD_d3d9.log)

**To Reproduce**
- Install RTX remix as usual. 
- Enable Fixed Function Rendering the settings and keep videos enabled.
- Launch the game

**Comment by nv-ajaus** [comment]
Hi @svelle , have you checked this game recently? I expect some of the issues for this title may have been fixed by general improvements since the 0.1.1 release.

From your image of the game playing, I noticed that the player's model is missing. A while ago we noticed that some applications will set index and vertex buffer bounds and then write beyond the boundaries. The Windows provided D3D9 would not care about the bounds, but we were being strict about the boundaries. Can you see if setting the "alwaysCopyEntireStaticBuffer" bridge configuration option to true makes the player model show up? The option should be available in the most recent bridge build.

I've noticed that the various FMV/VMR9/Overlay Mixer options have helped people with cutscene related crashes and black screens previously, specifically FMV and VMR9 on, and Overlay Mixer off. Can you try these and see if it helps with the cutscene issues or otherwise bypass the cutscenes if they don't help?

**Comment by svelle** [comment]
@nv-ajaus I have not, but I'll definitely try and play around with it again this weekend if I find some time and report back here. Thanks for following up!

**Comment by nv-ajaus** [comment]
Hi @svelle, did you have a chance to try it out?

**Comment by svelle** [comment]
hey @nv-ajaus  sorry, I was out sick for a bit but mostly back now.

I actually just gave it a try and found some improvements for sure!

So it's still not loading wihtout that extra tool, however if I load into the level now it seems like rtx remix is definitely catching all the level geometry. and some raytracing seems to work. The light source seems to be messed up still and the player model and also some ui elements are also not loading but I'll have to check the game settings to see if it's maybe related to something enabled/disabled there.

![2023-07-29_01-26](https://github.com/NVIDIAGameWorks/rtx-remix/assets/7526550/220be868-920f-4bb6-8fb1-e4ef7cdd0af6)
![2023-07-29_01-26_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/7526550/ac4e8017-97ac-438c-9f78-a50c2d60ada4)

**Comment by nv-ajaus** [comment]
I'm sorry to hear that, I hope you are keep feeling better.

Regarding the missing character, can you try out the "alwaysCopyEntireStaticBuffer" option I mentioned in https://github.com/NVIDIAGameWorks/rtx-remix/issues/80#issuecomment-1624476404 ? This looks like a case where that option might be helpful. Similarly that comment might contain some information on bypassing the intro videos.

**Comment by svelle** [comment]
Thanks, yeah feeling better alright :)

So I checked it just now and I think I don't have the most recent build as I seem to be missing this option. I'll do some more testing over the weekend and report back here as soon as I get it working.
One thing I can already say is that the video options stopped the game from crashing, which is nice!

Also if anyone has figured out how to make the character stop rotating whenever I open the dev menu I'd greatly appreciate any tips on that 😂

**Comment by nv-ajaus** [comment]
Hey @svelle, I'm going to go ahead and close this issue for now. If you try the "alwaysCopyEntireStaticBuffer" option and it ends up not solving the missing Lara issue, please fee free to reopen this issue.

**Comment by Speedwagen** [comment]
@nv-ajaus Hi. I am trying to find where to alwaysCopyEntireStaticBuffer. when you say in the bridge .conf, do I need to add this as rtx.alwaysCopyEntireStaticBuffer = 1?
if an application bypasses the bridge is this useless? 
I am trying to do this for AOTD but I am also checking another game too.
I noticed that in the log files it mentions "info:  [RTX-Compatibility-Info] Trying to raytrace but not detecting a valid camera."
Raytracing is working so I wonder if there is an additional render target.
https://github.com/NVIDIAGameWorks/dxvk-remix/issues/24 - this issue also highlights this.

**Comment by nv-ajaus** [comment]
Hi @Speedwagen, I didn't realize you posted after I closed the issue. In the `bridge.conf` file in the `.trex` folder, set `alwaysCopyEntireStaticBuffer = True`, with no leading `#`.
